version: '3.8'

services:
  duckduckgo-ai:
    build: .
    env_file:
      - .env
    container_name: duckduckgo-ai
    restart: always
    ports:
      - "8989:8080"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local